export const GET_INVENTORY = 'GET_INVENTORY';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_INVENTORY_WITH_RENTAL_DATES =
  'GET_INVENTORY_WITH_RENTAL_DATES';
